Debug
Signed-off-by: Scott Rigby <scott@r6by.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -40,6 +40,7 @@ jobs:
           echo "::set-output name=stable_dirs::$stable_dirs"
           incubator_dirs=$(echo ${{ steps.filter.outputs.incubator_files }} | xargs -n1 | cut -d/ -f 1-2 | sort -u | xargs)
           echo "::set-output name=incubator_dirs::$incubator_dirs"
+          echo "dirs: $stable_dirs"
 
   package:
     needs: changes
@@ -49,86 +50,87 @@ jobs:
       - name: package stable
         if: ${{ needs.changes.outputs.stable == 'true' }}
         run: |
-          mkdir -p ${{ runner.temp }}/stable/packages
-          for dir in ${{ needs.changes.outputs.stable_dirs }}; do
-              if helm dependency build stable/"$dir"; then
-                  helm package --destination ${{ runner.temp }}/stable/packages stable/"$dir"
-                  echo "✅ built dependencies and packaged stable/$dir"
-              else
-                  echo "❌ unable to build dependencies for stable/$dir"
-                  exit 1
-              fi
-          done
-      - uses: actions/upload-artifact@v2
-        if: ${{ needs.changes.outputs.stable == 'true' }}
-        with:
-          name: stable-packages
-          path: ${{ runner.temp }}/stable/packages/
-      - name: package incubator
-        if: ${{ needs.changes.outputs.incubator == 'true' }}
-        run: |
-          mkdir -p ${{ runner.temp }}/incubator/packages
-          for dir in ${{ needs.changes.outputs.incubator_dirs }}; do
-              if helm dependency build incubator/"$dir"; then
-                  helm package --destination ${{ runner.temp }}/incubator/packages incubator/"$dir"
-                  echo "✅ built dependencies and packaged incubator/$dir"
-              else
-                  echo "❌ unable to build dependencies for incubator/$dir"
-                  exit 1
-              fi
-          done
-      - uses: actions/upload-artifact@v2
-        if: ${{ needs.changes.outputs.incubator == 'true' }}
-        with:
-          name: stable-packages
-          path: ${{ runner.temp }}/incubator/packages/
+          echo "dirs: ${{ needs.changes.outputs.stable_dirs }}"
+  #         mkdir -p ${{ runner.temp }}/stable/packages
+  #         for dir in ${{ needs.changes.outputs.stable_dirs }}; do
+  #             if helm dependency build stable/"$dir"; then
+  #                 helm package --destination ${{ runner.temp }}/stable/packages stable/"$dir"
+  #                 echo "✅ built dependencies and packaged stable/$dir"
+  #             else
+  #                 echo "❌ unable to build dependencies for stable/$dir"
+  #                 exit 1
+  #             fi
+  #         done
+  #     - uses: actions/upload-artifact@v2
+  #       if: ${{ needs.changes.outputs.stable == 'true' }}
+  #       with:
+  #         name: stable-packages
+  #         path: ${{ runner.temp }}/stable/packages/
+  #     - name: package incubator
+  #       if: ${{ needs.changes.outputs.incubator == 'true' }}
+  #       run: |
+  #         mkdir -p ${{ runner.temp }}/incubator/packages
+  #         for dir in ${{ needs.changes.outputs.incubator_dirs }}; do
+  #             if helm dependency build incubator/"$dir"; then
+  #                 helm package --destination ${{ runner.temp }}/incubator/packages incubator/"$dir"
+  #                 echo "✅ built dependencies and packaged incubator/$dir"
+  #             else
+  #                 echo "❌ unable to build dependencies for incubator/$dir"
+  #                 exit 1
+  #             fi
+  #         done
+  #     - uses: actions/upload-artifact@v2
+  #       if: ${{ needs.changes.outputs.incubator == 'true' }}
+  #       with:
+  #         name: stable-packages
+  #         path: ${{ runner.temp }}/incubator/packages/
 
-  index-release:
-    needs: changes
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          ref: gh-pages
-      - name: configure Git
-        run: |
-          git config user.name "$GITHUB_ACTOR"
-          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
-      - uses: actions/download-artifact@v2
-        with:
-          name: stable-packages
-          path: ${{ runner.temp }}/stable/packages
-      - name: sync stable
-        if: ${{ needs.changes.outputs.stable == 'true' }}
-        run: |
-          if helm repo index --url https://charts.helm.sh/stable --merge stable/index.yaml ${{ runner.temp }}/stable; then
-              mv -f ${{ runner.temp }}/stable/index.yaml stable/index.yaml
-              git add stable/index.yaml
-          else
-              echo "❌ unable to update index"
-              exit 1
-          fi
-          mkdir -p stable/packages
-          cp -f ${{ runner.temp }}/stable/*.tgz stable/packages
-          git add stable/packages/*.tgz
-          git commit --signoff -m "Sync stable [ci skip]"
-          git push
-      - uses: actions/download-artifact@v2
-        with:
-          name: incubator-packages
-          path: ${{ runner.temp }}/incubator/packages
-      - name: sync incubator
-        if: ${{ needs.changes.outputs.incubator == 'true' }}
-        run: |
-          if helm repo index --url https://charts.helm.sh/incubator --merge incubator/index.yaml ${{ runner.temp }}/incubator; then
-              mv -f ${{ runner.temp }}/incubator/index.yaml incubator/index.yaml
-              git add incubator/index.yaml
-          else
-              echo "❌ unable to update index"
-              exit 1
-          fi
-          mkdir -p incubator/packages
-          cp -f ${{ runner.temp }}/incubator/*.tgz incubator/packages
-          git add incubator/packages/*.tgz
-          git commit --signoff -m "Sync incubator [ci skip]"
-          git push
+  # index-release:
+  #   needs: changes
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         ref: gh-pages
+  #     - name: configure Git
+  #       run: |
+  #         git config user.name "$GITHUB_ACTOR"
+  #         git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+  #     - uses: actions/download-artifact@v2
+  #       with:
+  #         name: stable-packages
+  #         path: ${{ runner.temp }}/stable/packages
+  #     - name: sync stable
+  #       if: ${{ needs.changes.outputs.stable == 'true' }}
+  #       run: |
+  #         if helm repo index --url https://charts.helm.sh/stable --merge stable/index.yaml ${{ runner.temp }}/stable; then
+  #             mv -f ${{ runner.temp }}/stable/index.yaml stable/index.yaml
+  #             git add stable/index.yaml
+  #         else
+  #             echo "❌ unable to update index"
+  #             exit 1
+  #         fi
+  #         mkdir -p stable/packages
+  #         cp -f ${{ runner.temp }}/stable/*.tgz stable/packages
+  #         git add stable/packages/*.tgz
+  #         git commit --signoff -m "Sync stable [ci skip]"
+  #         git push
+  #     - uses: actions/download-artifact@v2
+  #       with:
+  #         name: incubator-packages
+  #         path: ${{ runner.temp }}/incubator/packages
+  #     - name: sync incubator
+  #       if: ${{ needs.changes.outputs.incubator == 'true' }}
+  #       run: |
+  #         if helm repo index --url https://charts.helm.sh/incubator --merge incubator/index.yaml ${{ runner.temp }}/incubator; then
+  #             mv -f ${{ runner.temp }}/incubator/index.yaml incubator/index.yaml
+  #             git add incubator/index.yaml
+  #         else
+  #             echo "❌ unable to update index"
+  #             exit 1
+  #         fi
+  #         mkdir -p incubator/packages
+  #         cp -f ${{ runner.temp }}/incubator/*.tgz incubator/packages
+  #         git add incubator/packages/*.tgz
+  #         git commit --signoff -m "Sync incubator [ci skip]"
+  #         git push
