Debug
Signed-off-by: Scott Rigby <scott@r6by.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -33,12 +33,14 @@ jobs:
       #   "xargs" converts back to space-separated string
       - id: dirs
         run: |
-          echo "files: ${{ steps.filter.outputs.stable_files }}"
+          echo "stable files: ${{ steps.filter.outputs.stable_files }}"
+          echo "incubator files: ${{ steps.filter.outputs.stable_files }}"
           stable_dirs=$(echo ${{ steps.filter.outputs.stable_files }} | xargs -n1 | cut -d/ -f 1-2 | sort -u | xargs)
           echo "::set-output name=stable_dirs::$stable_dirs"
+          echo "stable dirs: $stable_dirs"
           incubator_dirs=$(echo ${{ steps.filter.outputs.incubator_files }} | xargs -n1 | cut -d/ -f 1-2 | sort -u | xargs)
           echo "::set-output name=incubator_dirs::$incubator_dirs"
-          echo "dirs: $stable_dirs"
+          echo "incubator dirs: $incubator_dirs"
 
   package:
     needs: changes
@@ -83,52 +85,52 @@ jobs:
           name: stable-packages
           path: ${{ runner.temp }}/incubator/packages/
 
-  # index-release:
-  #   needs: changes
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v2
-  #       with:
-  #         ref: gh-pages
-  #     - name: configure Git
-  #       run: |
-  #         git config user.name "$GITHUB_ACTOR"
-  #         git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
-  #     - uses: actions/download-artifact@v2
-  #       with:
-  #         name: stable-packages
-  #         path: ${{ runner.temp }}/stable/packages
-  #     - name: sync stable
-  #       if: ${{ needs.changes.outputs.stable == 'true' }}
-  #       run: |
-  #         if helm repo index --url https://charts.helm.sh/stable --merge stable/index.yaml ${{ runner.temp }}/stable; then
-  #             mv -f ${{ runner.temp }}/stable/index.yaml stable/index.yaml
-  #             git add stable/index.yaml
-  #         else
-  #             echo "❌ unable to update index"
-  #             exit 1
-  #         fi
-  #         mkdir -p stable/packages
-  #         cp -f ${{ runner.temp }}/stable/*.tgz stable/packages
-  #         git add stable/packages/*.tgz
-  #         git commit --signoff -m "Sync stable [ci skip]"
-  #         git push
-  #     - uses: actions/download-artifact@v2
-  #       with:
-  #         name: incubator-packages
-  #         path: ${{ runner.temp }}/incubator/packages
-  #     - name: sync incubator
-  #       if: ${{ needs.changes.outputs.incubator == 'true' }}
-  #       run: |
-  #         if helm repo index --url https://charts.helm.sh/incubator --merge incubator/index.yaml ${{ runner.temp }}/incubator; then
-  #             mv -f ${{ runner.temp }}/incubator/index.yaml incubator/index.yaml
-  #             git add incubator/index.yaml
-  #         else
-  #             echo "❌ unable to update index"
-  #             exit 1
-  #         fi
-  #         mkdir -p incubator/packages
-  #         cp -f ${{ runner.temp }}/incubator/*.tgz incubator/packages
-  #         git add incubator/packages/*.tgz
-  #         git commit --signoff -m "Sync incubator [ci skip]"
-  #         git push
+  index-release:
+    needs: changes
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          ref: gh-pages
+      - name: configure Git
+        run: |
+          git config user.name "$GITHUB_ACTOR"
+          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+      - uses: actions/download-artifact@v2
+        with:
+          name: stable-packages
+          path: ${{ runner.temp }}/stable/packages
+      - name: sync stable
+        if: ${{ needs.changes.outputs.stable == 'true' }}
+        run: |
+          if helm repo index --url https://charts.helm.sh/stable --merge stable/index.yaml ${{ runner.temp }}/stable; then
+              mv -f ${{ runner.temp }}/stable/index.yaml stable/index.yaml
+              git add stable/index.yaml
+          else
+              echo "❌ unable to update index"
+              exit 1
+          fi
+          mkdir -p stable/packages
+          cp -f ${{ runner.temp }}/stable/*.tgz stable/packages
+          git add stable/packages/*.tgz
+          git commit --signoff -m "Sync stable [ci skip]"
+          git push
+      - uses: actions/download-artifact@v2
+        with:
+          name: incubator-packages
+          path: ${{ runner.temp }}/incubator/packages
+      - name: sync incubator
+        if: ${{ needs.changes.outputs.incubator == 'true' }}
+        run: |
+          if helm repo index --url https://charts.helm.sh/incubator --merge incubator/index.yaml ${{ runner.temp }}/incubator; then
+              mv -f ${{ runner.temp }}/incubator/index.yaml incubator/index.yaml
+              git add incubator/index.yaml
+          else
+              echo "❌ unable to update index"
+              exit 1
+          fi
+          mkdir -p incubator/packages
+          cp -f ${{ runner.temp }}/incubator/*.tgz incubator/packages
+          git add incubator/packages/*.tgz
+          git commit --signoff -m "Sync incubator [ci skip]"
+          git push
