Debug
Signed-off-by: Scott Rigby <scott@r6by.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -26,76 +26,63 @@ jobs:
               - added|modified: 'stable/**'
             incubator:
               - added|modified: 'incubator/**'
-      - name: Test changes
-        id: dirs
-        if: ${{ steps.filter.outputs.stable == 'true' }}
-        run: |
-          echo "files: ${{ steps.filter.outputs.stable_files }}"
-          stable_dirs=$(echo ${{ steps.filter.outputs.stable_files }} | xargs -n1 | cut -d/ -f 1-2 | sort -u | xargs)
-          echo "::set-output name=stable_dirs::$stable_dirs"
-
       # Exports space-separated lists of changed chart dirs
       #   "xargs -n1" converts to newlines
       #   "cut -d/ -f 1-2" gets the first two dirs (example: stable/wordpress)
       #   "sort -u" gets sorted unique dirs
       #   "xargs" converts back to space-separated string
-      # - id: dirs
-      #   run: |
-      #     stable_dirs=$(echo ${{ steps.filter.outputs.stable_files }} | xargs -n1 | cut -d/ -f 1-2 | sort -u | xargs)
-      #     echo "::set-output name=stable_dirs::$stable_dirs"
-      #     incubator_dirs=$(echo ${{ steps.filter.outputs.incubator_files }} | xargs -n1 | cut -d/ -f 1-2 | sort -u | xargs)
-      #     echo "::set-output name=incubator_dirs::$incubator_dirs"
-      #     echo "dirs: $stable_dirs"
+      - id: dirs
+        if: ${{ steps.filter.outputs.stable == 'true' }}
+        run: |
+          echo "files: ${{ steps.filter.outputs.stable_files }}"
+          stable_dirs=$(echo ${{ steps.filter.outputs.stable_files }} | xargs -n1 | cut -d/ -f 1-2 | sort -u | xargs)
+          echo "::set-output name=stable_dirs::$stable_dirs"
+          incubator_dirs=$(echo ${{ steps.filter.outputs.incubator_files }} | xargs -n1 | cut -d/ -f 1-2 | sort -u | xargs)
+          echo "::set-output name=incubator_dirs::$incubator_dirs"
+          echo "dirs: $stable_dirs"
 
-  test:
+  package:
     needs: changes
     runs-on: ubuntu-latest
     steps:
-      - run: |
+      - uses: actions/checkout@v2
+      - name: package stable
+        if: ${{ needs.changes.outputs.stable == 'true' }}
+        run: |
           echo "dirs: ${{ needs.changes.outputs.stable_dirs }}"
-
-  # package:
-  #   needs: changes
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v2
-  #     - name: package stable
-  #       if: ${{ needs.changes.outputs.stable == 'true' }}
-  #       run: |
-  #         echo "dirs: ${{ needs.changes.outputs.stable_dirs }}"
-  #         mkdir -p ${{ runner.temp }}/stable/packages
-  #         for dir in ${{ needs.changes.outputs.stable_dirs }}; do
-  #             if helm dependency build stable/"$dir"; then
-  #                 helm package --destination ${{ runner.temp }}/stable/packages stable/"$dir"
-  #                 echo "✅ built dependencies and packaged stable/$dir"
-  #             else
-  #                 echo "❌ unable to build dependencies for stable/$dir"
-  #                 exit 1
-  #             fi
-  #         done
-  #     - uses: actions/upload-artifact@v2
-  #       if: ${{ needs.changes.outputs.stable == 'true' }}
-  #       with:
-  #         name: stable-packages
-  #         path: ${{ runner.temp }}/stable/packages/
-  #     - name: package incubator
-  #       if: ${{ needs.changes.outputs.incubator == 'true' }}
-  #       run: |
-  #         mkdir -p ${{ runner.temp }}/incubator/packages
-  #         for dir in ${{ needs.changes.outputs.incubator_dirs }}; do
-  #             if helm dependency build incubator/"$dir"; then
-  #                 helm package --destination ${{ runner.temp }}/incubator/packages incubator/"$dir"
-  #                 echo "✅ built dependencies and packaged incubator/$dir"
-  #             else
-  #                 echo "❌ unable to build dependencies for incubator/$dir"
-  #                 exit 1
-  #             fi
-  #         done
-  #     - uses: actions/upload-artifact@v2
-  #       if: ${{ needs.changes.outputs.incubator == 'true' }}
-  #       with:
-  #         name: stable-packages
-  #         path: ${{ runner.temp }}/incubator/packages/
+          mkdir -p ${{ runner.temp }}/stable/packages
+          for dir in ${{ needs.changes.outputs.stable_dirs }}; do
+              if helm dependency build stable/"$dir"; then
+                  helm package --destination ${{ runner.temp }}/stable/packages stable/"$dir"
+                  echo "✅ built dependencies and packaged stable/$dir"
+              else
+                  echo "❌ unable to build dependencies for stable/$dir"
+                  exit 1
+              fi
+          done
+      - uses: actions/upload-artifact@v2
+        if: ${{ needs.changes.outputs.stable == 'true' }}
+        with:
+          name: stable-packages
+          path: ${{ runner.temp }}/stable/packages/
+      - name: package incubator
+        if: ${{ needs.changes.outputs.incubator == 'true' }}
+        run: |
+          mkdir -p ${{ runner.temp }}/incubator/packages
+          for dir in ${{ needs.changes.outputs.incubator_dirs }}; do
+              if helm dependency build incubator/"$dir"; then
+                  helm package --destination ${{ runner.temp }}/incubator/packages incubator/"$dir"
+                  echo "✅ built dependencies and packaged incubator/$dir"
+              else
+                  echo "❌ unable to build dependencies for incubator/$dir"
+                  exit 1
+              fi
+          done
+      - uses: actions/upload-artifact@v2
+        if: ${{ needs.changes.outputs.incubator == 'true' }}
+        with:
+          name: stable-packages
+          path: ${{ runner.temp }}/incubator/packages/
 
   # index-release:
   #   needs: changes
